T2_QUISOCALA_KAREN/Models/Distribuidor.cs
using System.ComponentModel.DataAnnotations;

namespace T2_QUISOCALA_KAREN.Models
{
    public class Distribuidor
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="El Nombre de Distribuidor es obligatorio.")]
        public string NombreDistribuidor { get; set; }
        [Required(ErrorMessage ="La Razon Social es obligatoria.")]
        public string RazonSocial { get; set; }
        [Required(ErrorMessage ="El telefono es obligatorio.")]
        public int Telefono {  get; set; }
        [Required(ErrorMessage ="El Año Inicio de Distribucion es obligatorio.")]
        [Range(1900,3000,ErrorMessage = "El Año Inicio de Distribucion debe ser entre 1900 a 3000.")]
        public int? AnioInicioOperacion { get; set; }
        [Required(ErrorMessage ="El Contacto es obligatorio.")]
        public string Contacto { get; set; }
    }
}

T2_QUISOCALA_KAREN/Models/ErrorViewModel.cs
namespace T2_QUISOCALA_KAREN.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T2_QUISOCALA_KAREN/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;
using T2_QUISOCALA_KAREN.Datos;
using T2_QUISOCALA_KAREN.Models;

namespace T2_QUISOCALA_KAREN.Controllers
{
    public class DistribuidorController : Controller
    {
        public readonly ApplicationDbContext _db;
        public DistribuidorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Distribuidor> lista = _db.Distribuidor;
            return View(lista);
        }
        public IActionResult DistribuidoresDelPeru()
        {
            return View();
        }
        public IActionResult DistribuidoresDelMundo()
        {
            return View();
        }
        //Agregar
        public IActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Agregar(Distribuidor distribuidor)
        {
            if (ModelState.IsValid) 
            {
                _db.Distribuidor.Add(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);   
        }
        //Editar
        public IActionResult Editar(int? Id)
        {
            if (Id==null || Id==0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Update(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);
        }
        //Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Distribuidor distribuidor)
        {
            if (distribuidor==null)
            {
                return NotFound();
            }
            _db.Distribuidor.Remove(distribuidor);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

T2_QUISOCALA_KAREN/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using T2_QUISOCALA_KAREN.Models;

namespace T2_QUISOCALA_KAREN.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T2_QUISOCALA_KAREN/Views/Distribuidor/Agregar.cshtml
@model T2_QUISOCALA_KAREN.Models.Distribuidor
@{
    ViewData["Title"] = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agregar</h1>

<form method="post" asp-action="Agregar">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Nuevo Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control"/>
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razon Social</label>
                    <input asp-for="RazonSocial" class="form-control"/>
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Agregar Nuevo</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

T2_QUISOCALA_KAREN/Views/Distribuidor/DistribuidoresDelMundo.cshtml
@{
    ViewData["Title"] = "DistribuidoresDelMundo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Distribuidores del Mundo</h1>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Los Distribuidores más Conocidos en el Mundo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            background-color: #b3e0ff; /*fr*/
        }

        .distribuidor {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
            background-color: #fff; /*fb*/
        }

            .distribuidor img {
                width: 100px;
                height: auto;
                margin-right: 20px;
            }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Distribuidores más Conocidos en el Mundo</h1>

        <div class="distribuidor">
            <img src="https://www.stockinvestor.com/wp-content/uploads/walmart-store-front_129826456676858078.jpg" alt="Logo Walmart">
            <div>
                <h3>Walmart</h3>
                <p>Walmart es una de las empresas más influyentes del mundo, conocida por su capacidad para ofrecer productos a precios competitivos y su extensa red de distribución global.</p>
            </div>
        </div>

        <div class="distribuidor">
            <img src="https://nypost.com/wp-content/uploads/sites/2/2020/04/amazon-feature.jpg?quality=90&strip=all&w=744" alt="Logo Amazon">
            <div>
                <h3>Amazon</h3>
                <p>Amazon es una de las empresas más influyentes y diversificadas del mundo, conocida por su enfoque en la innovación, la eficiencia y la satisfacción del cliente. Su capacidad para reinventarse continuamente ha consolidado su posición como un líder en múltiples sectores, desde el comercio electrónico hasta la tecnología y la logística.</p>
            </div>
        </div>
    </div>
</body>
</html>

T2_QUISOCALA_KAREN/Views/Distribuidor/DistribuidoresDelPeru.cshtml
@{
    ViewData["Title"] = "DistribuidoresDelPeru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Distribuidores del Perú</h1>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Los Distribuidores más Conocidos en el Perú</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            background-color: #ffcccc; 
        }

        .distribuidor {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
            background-color: #fff;
        }

            .distribuidor img {
                width: 100px;
                height: auto;
                margin-right: 20px;
            }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Distribuidores más Conocidos en el Perú</h1>

        <div class="distribuidor">
            <img src="https://i.ytimg.com/vi/DeekLuSHqPg/maxresdefault.jpg" alt="Logo Grupo Romero">
            <div>
                <h3>Grupo Romero</h3>
                <p>El Grupo Romero es uno de los conglomerados empresariales más grandes y diversificados de Perú, con actividades en sectores como agroindustria, pesca, logística, energía y más.</p>
            </div>
        </div>

        <div class="distribuidor">
            <img src="https://construex.com.ec/images/upload/454/org/5a78c79a1e91c4.63525038.png" alt="Logo UNACEM">
            <div>
                <h3>UNACEM</h3>
                <p>UNACEM es una de las principales empresas cementeras del Perú, que produce y distribuye cemento, agregados y concreto para el sector de la construcción en el país.</p>
            </div>
        </div>
    </div>
</body>
</html>

T2_QUISOCALA_KAREN/Views/Distribuidor/Editar.cshtml
@model T2_QUISOCALA_KAREN.Models.Distribuidor

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<form method="post" asp-action="Editar">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razon Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_QUISOCALA_KAREN/Views/Distribuidor/Eliminar.cshtml
@model T2_QUISOCALA_KAREN.Models.Distribuidor

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<form method="post" asp-action="Eliminar">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">¿Esta seguro de Eliminar este Distribuidor?</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razon Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Eliminar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_QUISOCALA_KAREN/Views/Distribuidor/Index.cshtml
@model IEnumerable<T2_QUISOCALA_KAREN.Models.Distribuidor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Distribuidores</h2>
        </div>
        <div class=col-6>
            <a asp-controller="Distribuidor" asp-action="Agregar" class="btn btn-primary">Nuevo Distribuidor</a>
        </div>
    </div>

    <br/>

    @if (Model.Count() >0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre Distribuidor</th>
                    <th>Razòn social</th>
                    <th>Telefono</th>
                    <th>Año Inicio de Operaciòn </th>
                    <th>Contacto</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <th widht="60%">@item.NombreDistribuidor</th>
                        <th widht="50%">@item.RazonSocial</th>
                        <th widht="40%">@item.Telefono</th>
                        <th widht="30%">@item.AnioInicioOperacion</th>
                        <th widht="20%">@item.Contacto</th>
                        <th>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Distribuidor" asp-action="Editar" asp-route-Id="@item.Id" class="btn btn-primary mx-2">Editar</a>
                                <a asp-controller="Distribuidor" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">Eliminar</a>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay registros de Distruidor</p>
    }
</div>

T2_QUISOCALA_KAREN/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

T2_QUISOCALA_KAREN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_QUISOCALA_KAREN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T2_QUISOCALA_KAREN.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_QUISOCALA_KAREN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="DistribuidoresDelPeru">Distribuidores del Perú</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="DistribuidoresDelMundo">Distribuidores del Mundo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - T2_QUISOCALA_KAREN - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>